export const IS_LOADING = 'IS_LOADING';
export const CALCULATE_COORDINATES = 'CALCULATE_COORDINATES';
export const SAVE_COORDINATES = 'SAVE_COORDINATES';
export const SAVE_CITY = 'SAVE_CITY';
export const SAVE_TIMINGS = 'SAVE_TIMINGS';
